export const ADD_PRODUCT_CART ='ADD_PRODUCT_CART';
export const GET_NUMBERS_PRODUCT ='GET_NUMBERS_PRODUCT' ;
export const GET_ARTICLES ='GET_ARTICLES';
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_ITEM_QTY ="ADJUST_ITEM_QTY";
export const GET_CART="GET_CART";
export const INCREASE_QUANTITY ="INCREASE_QUANTITY";
export const DECREASE_QUANTITY ="INCREASE_QUANTITY";



