export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const PRE_REGISTRATION="PRE_REGISTRATION";
export const DELETE_PREUSER="DELETE_PREUSER";

